### ISSUE TITLE
A possible Integer overflow at UPRN EF Core entity class field!

### ISSUE THREAD

**Issue by Duslerke** [LBHackney-IT/lbh-fss-public-api#29]
Here is the definition of the UPRN field in the EF Core Service Location infrastructure entity:

https://github.com/LBHackney-IT/lbh-fss-public-api/blob/2e6fff9cb37ec8de3a38dd7358d85ff1f880b6a3/LBHFSSPublicAPI/V1/Infrastructure/ServiceLocation.cs#L11

A maximum value of a 32bit integer, which is a type in use within this example is: `2'147'483'647`, which is documented [here](https://docs.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=netcore-3.1). Essentially, it doesn't go higher than `10 digits`!

While making requests to [Address API](https://github.com/LBHackney-IT/HackneyAddressesAPI) via postman, I noticed that the returned **UPRN** numbers **are** `from  11 to 12` digits long. _Unfortunatelly I can't share the screenshot as it's likely a sensitive data._

I'm raising this issue because I foresee that whenever our API is going to get by the real UPRN data, it's likely to crash with Integer overflow errors. I'll raise this issue on the [FSS Portal API](https://github.com/LBHackney-IT/lbh-fss-portal-api) as it contains the same EF Core entities implementation.

**Comment by LBHSPreston** [comment]
Issue addressed in PR £38.
